vsphere_server             = ""
vsphere_user               = ""
vsphere_password           = ""
vsphere_datacenter         = ""
vsphere_datastore          = ""
vsphere_cluster            = ""
vsphere_network            = ""
vsphere_minio_instance_ip  = ""
